app:
  name: Live2d——Agent
  version: 1.0.0
llm:
  api_key: 
  base_url: https://api.moonshot.cn/v1
  model: qwen3.5:2b
  temperature: 0.3
  max_memory: 30
  prompt_file:
weather:
  api_key: 
  city_code: 
tts:
  api_url: http://127.0.0.1:9880/tts
  output_file:
  ref_audio_path:
  prompt_text:
  prompt_lang: en
  text_lang: zh
  text_split_method: cut2
  batch_size: 1
  media_type: wav
  streaming_mode: false
live2d:
  websocket_uri: ws://127.0.0.1:10086/api
  default_expression: normal
  expressions_path: expressions/
audio_record:
  chunk: 1024
  format: paInt16
  channels: 1
  rate: 44100
  default_output: record.wav
  max_duration: 20
vad:
  chunk: 1024
  format: paInt16
  channels: 1
  rate: 16000
  threshold: 1000
  speech_timeout: 10.0
  min_speech_duration: 0.8
  silence_limit: 1.5
  pre_speech: 1
  temp_recording_prefix: temp_recording_
asr:
  model: paraformer-zh
  vad_model: fsmn-vad
  punc_model: ct-punc-c
  spk_model: cam++
  default_audio_path: 
email:
  imap_server: imap.qq.com
  ssl: true
  port: 993
  username: 
  password: 
  folder: INBOX
  check_interval: 1
game:
  process_names: [["cloudmusic.exe","网易云音乐"], ["steam.exe","steam平台"],["BsgLauncher.exe","逃离塔科夫"],["bf6.exe","战地风云6"],["SlayTheSpire2.exe","杀戮尖塔2"]]
  check_interval: 2
ui:
  title: Live2d_Agent
  default_style:
    user_message_bg: '#95EC69'
    ai_message_bg: '#FF0'
    text_color: '#000'
    timestamp_color: '#999'
    font_size: 14
    expression_size: 20%
rag:
  host: localhost
  prot: 6333
  SentenceTransformer: 'shibing624/text2vec-base-chinese'
graph:
  neo4j_url: neo4j://localhost:7475
  username: 
  password: 